name: deploy-toy-website-environments    
concurrency: toy-company    
    
on:    
  push:    
    branches:    
      - main    
  workflow_dispatch:    
    inputs:    
      environmentType:    
        required: true    
        type: string    
      resourceGroupName:    
        required: true    
        type: string    
    
env:    
  TESTCRED: ${{ secrets.AZURE_TEST_CRED }}    
  PRODCRED: ${{ secrets.AZURE_PROD_CRED }}    
    
permissions:    
  id-token: write    
  contents: read    
    
jobs:    
    
  # Lint the Bicep file.    
  lint:    
    uses: ./lint.yml@main  
    
  # Deploy to the test environment.    
  deploy-test:    
    needs: lint  
    uses: ./deploy.yml@main  
    env:  
      AZURE_CRED: ${{ secrets.AZURE_TEST_CRED }}  
    with:    
      environmentType: 'Test'  
      resourceGroupName: 'ToyWebsiteTest'  
    
  # Deploy to the production environment.    
  deploy-production:    
    needs: deploy-test    
    uses: ./deploy.yml@main  
    env:  
      AZURE_CRED: ${{ secrets.AZURE_PROD_CRED }}  
    with:    
      environmentType: 'Production'  
      resourceGroupName: 'ToyWebsiteProduction' 