name: deploy-toy-website-environments      
concurrency: toy-company      
      
on:      
  push:      
    branches:      
      - main  
  workflow_call:  
  workflow_dispatch:      
    inputs:      
      environmentType:      
        required: true      
        type: string      
      resourceGroupName:      
        required: true      
        type: string      
      
permissions:      
  id-token: write      
  contents: read      
env:
  TEMPLATE: deploy/main.bicep
  RESOURCE_GROUP: ToyWebsite-test
  PROD_RESOURCEGROUP: ToyWebsite-Production
  TEST_CRED: secret.AZURE_TEST_CRED
  PROD_CRED: secret.AZURE_PROD_CRED      
jobs:      
      
  # Lint the Bicep file.    
  lint:    
    runs-on: ubuntu-latest  
    steps:    
    - name: Lint Bicep file    
      run: ./.github/workflows/lint.yml  
    
  # Deploy to the test environment.      
  deploy-test:      
    needs: lint      
    runs-on: ubuntu-latest    
    steps:    
    - name: Login to Azure      
      uses: azure/login@v1      
      with:      
        creds: ${{ env.TEST_CRED }}      
    - name: Deploy to test environment      
      uses: azure/arm-deploy@1      
      with:      
        resource-group: ${{ env.RESOURCE_GROUP }}      
        template: ${{ env.TEMPLATE }}      
        deployment-mode: 'incremental'      
        app-name: ${{env.RESOURCE_GROUP}}      
      
  # Deploy to the production environment.      
  deploy-production:      
    needs: deploy-test      
    runs-on: ubuntu-latest    
    steps:    
    - name: Login to Azure      
      uses: azure/login@v1      
      with:      
        creds: ${{ secrets.AZURE_PROD_CRED }}      
    - name: Deploy to production environment      
      uses: azure/arm-deploy@1      
      with:      
        resource-group: ${{ env.PROD_RESOURCEGROUP }}      
        template: ${{ env.TEMPLATE }}      
        deployment-mode: 'incremental'      
        app-name: ${{ env.PROD_RESOURCEGROUP }}            
