name: deploy-toy-website-environments      
concurrency: toy-company      
      
on:      
  push:      
    branches:      
      - main  
  workflow_call:  
  workflow_dispatch:      
    inputs:      
      environmentType:      
        required: true      
        type: string      
      resourceGroupName:      
        required: true      
        type: string      
      
permissions:      
  id-token: write      
  contents: read      
      
jobs:      
      
  # Lint the Bicep file.    
  lint:    
    runs-on: ubuntu-latest  
    uses: ./.github/workflows/lint.yml  
    
  # Deploy to the test environment.      
  deploy-test:      
    needs: lint      
    runs-on: ubuntu-latest    
    steps:    
    - name: Deploy to test environment    
      uses: ./.github/workflows/deploy.yml    
      with:    
        app-name: 'toy-website-test'    
      
  # Deploy to the production environment.      
  deploy-production:      
    needs: deploy-test      
    runs-on: ubuntu-latest    
    steps:    
    - name: Deploy to production environment    
      uses: ./.github/workflows/deploy.yml    
      with:    
        app-name: 'toy-website-production'  
